INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 1', '2023-06-18 15:56:36', 'praesent blandit nam nulla integer pede', 1);
INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 2', '2023-06-14 12:54:23', 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 2);
INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 3', '2023-06-16 08:23:36', 'in hac habitasse platea dictumst etiam', 1);
INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 4', '2023-06-22 11:54:20', 'consectetuer eget rutrum at lorem integer tincidunt ante', 3);
INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 5', '2023-06-23 23:58:14', 'nulla dapibus dolor vel est donec odio justo sollicitudin', 2);
INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 6', '2023-06-20 16:53:21', 'lectus vestibulum quam sapien varius ut', 1);
INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 7', '2023-06-07 06:31:20', 'purus phasellus in felis donec semper sapien', 3);
INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 8', '2023-06-11 07:38:56', 'mauris viverra diam vitae quam', 1);
INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 9', '2023-06-15 12:31:42', 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 3);
INSERT INTO task (task_name, task_creation_date, task_description, task_order) VALUES ('Task 10', '2023-06-18 03:06:52', 'enim blandit mi in porttitor pede justo eu', 3);
